//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Trejo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Prueba_TrejoEntities : DbContext
    {
        public Prueba_TrejoEntities()
            : base("name=Prueba_TrejoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<person> person { get; set; }
    
        public virtual ObjectResult<persona_Result> persona()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<persona_Result>("persona");
        }
    }
}
